name: After Pages deploy smoke-test

on:
  push:
    branches: [ gh-pages ]

jobs:
  smoke-after-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Wait briefly for Pages
        run: sleep 6
      - name: Determine site URL from gh-pages CNAME
        id: determine
        run: |
          set -e
          URL="https://tlacy.github.io"
          # Try to read CNAME file from gh-pages branch
          git clone --depth=1 --branch gh-pages https://github.com/${{ github.repository }} ghp || true
          if [ -f ghp/CNAME ]; then
            C=$(cat ghp/CNAME | tr -d '\n' );
            if [ -n "$C" ]; then URL="https://$C"; fi
          fi
          echo "SITE_URL=$URL" >> "$GITHUB_OUTPUT"
      - name: Check published site
        run: |
          set -e
          URL="${{ steps.determine.outputs.SITE_URL }}"
          for i in 1 2 3 4 5; do
            if curl -sSf "$URL" >/dev/null 2>&1; then break; fi
            sleep 2
          done
          curl -sSf "$URL" | grep -i "Tom Lacy" || (echo 'Smoke failed: hero missing' && exit 1)
