name: Deploy to GitHub Pages (opt-in)

# This workflow is intentionally opt-in. It only runs when the `ENABLE_PAGES_DEPLOY` secret
# is set to `true` in repository secrets or when the `force` input is provided from workflow_dispatch.

on:
  push:
    branches: [ main ]
  # Default: manual dispatch also supported.
  workflow_dispatch:
    inputs:
      force:
        description: 'Force deploy (manual run)'
        required: false
        default: 'false'

jobs:
  deploy:
    name: Deploy (opt-in)
    runs-on: ubuntu-latest
    # Determine at runtime whether to proceed. The following step sets outputs.should_deploy
    # to 'true' when the run was manually dispatched or when the repo secret
    # ENABLE_PAGES_DEPLOY is set to 'true'. This avoids using `secrets` in job-level `if`.
    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}
    steps:
      - name: Check opt-in for automatic deploys
        id: check
        run: |
          # If manual dispatch, allow deploy.
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "should_deploy=true" >> "$GITHUB_OUTPUT"
            echo "Manual dispatch: allowing deploy."
            exit 0
          fi
          # For pushes, require the presence of a repository opt-in file: .github/pages-deploy-enabled
          if [ "${{ github.event_name }}" = "push" ] && [ -f ".github/pages-deploy-enabled" ]; then
            echo "should_deploy=true" >> "$GITHUB_OUTPUT"
            echo ".github/pages-deploy-enabled found: allowing automatic deploy."
            exit 0
          fi
          echo "should_deploy=false" >> "$GITHUB_OUTPUT"
          echo "Automatic deploy disabled. To enable automatic deploys on push, add a file named .github/pages-deploy-enabled to the repository (commit to main)."
          exit 0
      - name: Checkout
        if: steps.check.outputs.should_deploy == 'true'
        uses: actions/checkout@v4

      - name: Build (none)
        if: steps.check.outputs.should_deploy == 'true'
        run: echo 'No build step; site is static'

      - name: Deploy to GitHub Pages
        if: steps.check.outputs.should_deploy == 'true'
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
        # Note: this action will push to gh-pages by default unless configured otherwise.
        # If you prefer Pages from main (root), don't use this workflow; instead configure Pages in repo settings.

      - name: Post-deploy note
        if: steps.check.outputs.should_deploy == 'true'
        run: |
          echo 'If you used this workflow, confirm Pages settings in repository > Settings > Pages.'
