name: Link check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check homepage links
        run: |
          set -e
          URL="https://tlacy.github.io"
          echo "Checking $URL"
          curl -sSf "$URL" -o /tmp/home.html
          # extract hrefs and check
          grep -oP 'href="\K[^"]+' /tmp/home.html | grep -v '^#' | sort -u | while read u; do
            if echo "$u" | grep -q '^http'; then
              echo "Checking $u"; curl -sSfI "$u" >/dev/null || (echo "Broken: $u" && exit 1)
            else
              # relative link
              full="$URL/${u#./}"
              echo "Checking $full"; curl -sSfI "$full" >/dev/null || (echo "Broken: $full" && exit 1)
            fi
          done
