name: Smoke tests (static site)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start static server
        run: |
          python3 -m http.server 8000 &
          sleep 1

      - name: Check homepage
        run: |
          set -e
          # Wait briefly for server
          for i in 1 2 3 4 5; do
            if curl -sSf http://localhost:8000 >/dev/null 2>&1; then break; fi
            sleep 1
          done
          curl -sSf http://localhost:8000 | grep -i "Tom" || (echo 'Smoke test failed: homepage did not contain expected text' && exit 1)
